/**
 * One-off generator for the spike fixture assets (task 1.2). Produces a
 * synthetic 2-frame RGBA strip PNG plus the three module-graph wrappers the
 * four transport candidates need, entirely from Node built-ins (zlib) — no
 * dependency on an image library. Re-run with `node build-fixture.mjs` if the
 * fixture ever needs regenerating; the outputs are checked in so the spike
 * harness has no first-run generation step.
 *
 * Not shipped: this whole `scripts/` tree is dev tooling, never part of
 * `dist/pet-2d/`.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateSync } from 'node:zlib';

const here = path.dirname(fileURLToPath(import.meta.url));

// ---- minimal PNG encoder (RGBA, filter-none, single IDAT) ----------------

const CRC_TABLE = (() => {
  const table = new Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buf) {
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) crc = CRC_TABLE[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const typeBuf = Buffer.from(type, 'ascii');
  const lenBuf = Buffer.alloc(4);
  lenBuf.writeUInt32BE(data.length, 0);
  const crcInput = Buffer.concat([typeBuf, data]);
  const crcBuf = Buffer.alloc(4);
  crcBuf.writeUInt32BE(crc32(crcInput), 0);
  return Buffer.concat([lenBuf, typeBuf, data, crcBuf]);
}

/** @param {(x:number,y:number)=>[number,number,number,number]} pixelAt */
function encodePng(width, height, pixelAt) {
  const sig = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);

  const ihdrData = Buffer.alloc(13);
  ihdrData.writeUInt32BE(width, 0);
  ihdrData.writeUInt32BE(height, 4);
  ihdrData[8] = 8; // bit depth
  ihdrData[9] = 6; // color type: RGBA
  ihdrData[10] = 0; // compression
  ihdrData[11] = 0; // filter
  ihdrData[12] = 0; // interlace
  const ihdr = chunk('IHDR', ihdrData);

  const stride = 1 + width * 4; // filter byte + RGBA row
  const raw = Buffer.alloc(stride * height);
  for (let y = 0; y < height; y++) {
    const rowStart = y * stride;
    raw[rowStart] = 0; // filter: none
    for (let x = 0; x < width; x++) {
      const [r, g, b, a] = pixelAt(x, y);
      const px = rowStart + 1 + x * 4;
      raw[px] = r;
      raw[px + 1] = g;
      raw[px + 2] = b;
      raw[px + 3] = a;
    }
  }
  const idat = chunk('IDAT', deflateSync(raw));
  const iend = chunk('IEND', Buffer.alloc(0));
  return Buffer.concat([sig, ihdr, idat, iend]);
}

// ---- fixture content: 2-frame 256x256 strip (512x256 total) --------------
// frame 0 (x 0..255)   = opaque red,  corner pixel (0,0) fully transparent
// frame 1 (x 256..511) = opaque blue, corner pixel (256,0) fully transparent
// The transparent corners give getImageData something non-trivial to read
// back even though this fixture's only job is canvas-taint testing, not
// alpha-quality (that's item ③, against the real whale-girl PNG).
const FRAME = 256;
const png = encodePng(FRAME * 2, FRAME, (x, y) => {
  const frame = x < FRAME ? 0 : 1;
  const isCorner = y === 0 && (x === 0 || x === FRAME);
  if (isCorner) return [0, 0, 0, 0];
  return frame === 0 ? [220, 40, 40, 255] : [40, 90, 220, 255];
});

writeFileSync(path.join(here, 'sheet.png'), png);

const manifest = {
  id: 'spike-fixture',
  frames: 2,
  frameSize: FRAME,
  note: 'synthetic 2-frame strip generated by build-fixture.mjs for spike item 1 only',
};
writeFileSync(path.join(here, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

const base64 = png.toString('base64');
const sheetsJson = {
  sheet: { base64, mime: 'image/png', frames: 2, frameSize: FRAME },
};
writeFileSync(path.join(here, 'sheets.json'), JSON.stringify(sheetsJson, null, 2) + '\n');

const dataUri = `data:image/png;base64,${base64}`;
const packMjs = `// Generated by build-fixture.mjs — candidate (d): a pack module exporting a
// data URI directly, the D1-predicted-safe transport (module graph, no
// separate byte fetch).
export default ${JSON.stringify(dataUri)};
`;
writeFileSync(path.join(here, 'pack.mjs'), packMjs);

console.log(`fixture written: sheet.png (${png.length} bytes), manifest.json, sheets.json, pack.mjs`);
